# Generated by Django 3.2.23 on 2023-11-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miaplicacion', '0002_autor_poema'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='biografia',
            field=models.TextField(default='Esta es la biografía del autor'),
        ),
    ]
