# Generated by Django 3.2.23 on 2023-11-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miaplicacion', '0005_poema_leido'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
