# Generated by Django 3.2.23 on 2023-11-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miaplicacion', '0007_auto_20231115_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='megusta',
            field=models.IntegerField(default=0),
        ),
    ]
