# Generated by Django 3.2.23 on 2023-11-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miaplicacion', '0009_auto_20231115_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
    ]
