# Generated by Django 3.2.23 on 2023-11-15 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miaplicacion', '0010_proyecto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='autor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='miaplicacion.autor'),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='megusta',
            field=models.IntegerField(default=0),
        ),
    ]
